</div>
<div class="jumbotron">
    <div class="container">
        <h1><?php echo sprintf($this->translate('Welcome to %sFood280%s'), '<span class="zf-green">', '</span>') ?></h1>
        <p><?php echo sprintf($this->translate('Find, share, collaborate: The social cooking experience for people who don\'t know what to eat')) ?></p>
        <p><a class="btn btn-success btn-lg" href="/user/register"><?php echo $this->translate('Get Started') ?> &raquo;</a></p>
        <p>Or, if you&apos;re already joined, <a href="/user/login">sign in.</a></p>
    </div>
</div>

<div class="container">
<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Eggs and meat so much to eat') ?></h3>
            </div>
            <div class="panel-body">
                <p>SPAM SPAM SPAM SPAM SPAM SPAM SPAM SPAM EGGS SPAM SPAMSPAM SPAM SPAM SPAM SPAM SPAM SPAM SPAM EGGS SPAM SPAMSPAM SPAM SPAM SPAM SPAM SPAM SPAM SPAM EGGS SPAM SPAMSPAM SPAM SPAM SPAM SPAM SPAM SPAM SPAM EGGS SPAM SPAMSPAM SPAM SPAM SPAM SPAM SPAM SPAM SPAM EGGS SPAM SPAMSPAM SPAM SPAM SPAM SPAM SPAM SPAM SPAM EGGS SPAM SPAM</p>
                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank"><?php echo $this->translate('More features!') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

</div>
