</div>
<div class="jumbotron">
    <div class="container">
        <h1><?php echo sprintf($this->translate('Welcome to %sFood280%s'), '<span class="zf-green">', '</span>') ?></h1>
        <p><?php echo sprintf($this->translate('Find, share, collaborate: The social cooking experience for people who don\'t know what to eat')) ?></p>
        <p><a class="btn btn-success btn-lg" href="/user/register"><?php echo $this->translate('Get Started') ?> &raquo;</a></p>
        <p>Or, if you&apos;re already joined, <a href="/user/login">sign in.</a></p>
    </div>
</div>

<div class="container">
<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Search Recipes!') ?></h3>
            </div>
            <div class="panel-body">
                <p>Search for new ways to make your favorite foods, or find new foods based on what you have in your house right now. It's fast and easy to find something according to your tastes.</p>
                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank"><?php echo $this->translate('Yay!') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Keep track of what you have') ?></h3>
            </div>
            <div class="panel-body">
                <p>Ever found it hard to keep track of what you have on hand? With Food280 you can keep a constant log of the food you've used. Just enter it in and then filter your searches based on it. </p>
                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank"><?php echo $this->translate('More!') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('What&apos;s for Dinner?') ?></h3>
            </div>
            <div class="panel-body">
                <p>You get home from work or school and wonder what you want to eat? Why do you want to eat it? I can't think of anything else to put here so just use this feature and GO!</p>
                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank"><?php echo $this->translate('More features!') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

</div>
