<?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'Edit album';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $addForm = $this->form;
 $addForm->setAttribute('action', $this->url(
     'album',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $addForm->prepare();

 echo $this->form()->openTag($addForm);
 echo $this->formHidden($addForm->get('id'));
 echo $this->formRow($addForm->get('title'));
 echo $this->formRow($addForm->get('artist'));
 echo $this->formSubmit($addForm->get('submit'));
 echo $this->form()->closeTag();