<?php
$title = 'Fridge';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>


<div class="row">
    <div class="col-md-2">
<!--        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Sort Options</h3>
            </div>
            <div class="panel-body">
                <div class="well-sm">sort1</div>
                <div class="well-sm">sort2</div>
                <div class="well-sm">sort3</div>
                <div class="well-sm"><div class="pull-right"><input type="button" value="sort"/></div></div>
            </div>
        </div>-->
<?php
                        $searchForm->setAttribute('action', $this->url('fridge', array('action' => 'index')));
                        $searchForm->prepare();

                        echo $this->form()->openTag($searchForm);
                    ?>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Find in Fridge</h3>
            </div>
            <div class="panel-body">
                <?php echo $this->formHidden($searchForm->get('userID')); ?>
                <?php  echo $this->formElement($searchForm->get('searchValue')); ?>
                
                <div class="well-sm">
                    <div class="pull-right">
                        <?php  echo $this->formElement($searchForm->get('submitSearch')); ?>
                        
                    </div>
                </div>
            </div>
        </div>

    </div>
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    Items in your Fridge
                    <div class="pull-right"><?php  echo $this->formElement($searchForm->get('submitAll')); ?></div>
                </h3>
                
            </div>
            <?php echo $this->form()->closeTag(); ?> 
            <div class="panel-body">
                <ul class="list-group">
                    <?php foreach ($this->paginator as $item): ?> 
                    <?php
                        $updateForm->setAttribute('action', $this->url('fridge', array('action' => 'index')));
                        $updateForm->prepare();

                        echo $this->form()->openTag($updateForm);
                    ?>

                    <?php   
                            
                    
//                            //echo $this->formHidden($addForm->get('itemID'));
//                            $itemID = $this->formHidden($addForm->get('itemID'));
//                            $itemID->setAttribute(array('value' => '2'));
//                            echo $itemID;
//
                            echo $this->formHidden($updateForm->get('itemID'));
                            echo $this->formHidden($updateForm->get('userID'));
                            echo $this->formHidden($updateForm->get('itemName'));
                            echo $this->formHidden($updateForm->get('itemAmount'));
                            echo $this->formHidden($updateForm->get('amountType'));
                            echo $this->formHidden($updateForm->get('expireDate'));
                            
                            echo $this->formElementErrors($updateForm->get('itemID'));
                            echo $this->formElementErrors($updateForm->get('itemName'));
                            echo $this->formElementErrors($updateForm->get('itemAmount'));
                            echo $this->formElementErrors($updateForm->get('amountType'));
                            echo $this->formElementErrors($updateForm->get('expireDate'));
                            echo $this->formElementErrors($updateForm->get('userID'));
                        ?>  
                    <input type="hidden" name="itemID" id="itemID" value="<?php echo $this->escapeHtml($item->itemID); ?>"> 
                    <input type="hidden" name="itemName" id="itemName" value="<?php echo $this->escapeHtml($item->itemName); ?>">
                    <input type="hidden" name="itemAmount" id="itemAmount" value="<?php echo $this->escapeHtml($item->itemAmount); ?>">
                    <input type="hidden" name="amountType" id="amountType" value="<?php echo $this->escapeHtml($item->amountType); ?>">
                    <input type="hidden" name="expireDate" id="expireDate" value="<?php echo $this->escapeHtml($item->expireDate); ?>">
                        <li class="list-group-item">
                            <div class="well-sm">
                                <?php //echo $this->escapeHtml($item->itemID); ?>
                                
                                <?php echo $this->escapeHtml($item->itemName); ?>
                                
                                <div class="pull-right">
                                    <?php echo $this->escapeHtml($item->itemAmount) . " " . $this->escapeHtml($item->amountType); ?> 


                                    <div id="update-btn" class="btn-group">
                                        <?php  echo $this->formElement($updateForm->get('submitPlus')); ?>
                                        <?php  echo $this->formElement($updateForm->get('submitMinus')); ?>
                                        <?php // echo $this->formElement($updateForm->get('submitRemove')); ?>
                                        
                                    </div>

                                    <?php echo $this->escapeHtml($item->expireDate); ?>
                                </div>
                            </div>
                        </li>
                     <?php echo $this->form()->closeTag(); ?>   
                    <?php endforeach; ?>
                    </ul>    
                            <?php
                                // add at the end of the file after the table
                                echo $this->paginationControl(
                                    // the paginator object
                                    $this->paginator,
                                    // the scrolling style
                                    'sliding',
                                    // the partial to use to render the control
                                    array('partial/paginator.phtml', 'Fridge'),
                                    // the route to link to when a user clicks a control link
                                    array(
                                        'route' => 'fridge'
                                    )
                                );
                            ?>
                        
                
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <?php
        $addForm->setAttribute('action', $this->url('fridge', array('action' => 'index')));
        $addForm->prepare();

        echo $this->form()->openTag($addForm);
        echo $this->formHidden($addForm->get('userID'));
        echo $this->formHidden($addForm->get('itemID'));
        ?>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Add Item to the Fridge</h3>
            </div>
            <div class="panel-body">
                <ul class="list-group">
                    <li class="list-group-item">
                        <div class="well-sm">
                            Item Name
                            <div class="pull-right">
                                <?php echo $this->formElement($addForm->get('itemName')); ?>
                            </div>
                        </div>
                        <div id="nameError"><?php
                        $itemNameErr = $this->formElementErrors($addForm->get('itemName'), array('class' => 'help-inline'));
                        if ($itemNameErr != ''):
                            ?>
                            <div class="well-sm"><?php echo $itemNameErr; ?></div>
                        <?php endif ?></div>
                    </li>

                    <li class="list-group-item">Time (estimate)
                        <ul>
                            <li>
                                <div class="well-sm">
                                    Amount
                                    <div class="pull-right">
                                        <?php echo $this->formElement($addForm->get('itemAmount')); ?>
                                        <?php echo $this->formElement($addForm->get('amountType')); ?>
                                    </div>
                                    <?php
                                    $itemAmountErr = $this->formElementErrors($addForm->get('itemAmount'), array('class' => 'help-inline'));
                                    if ($itemAmountErr != ''):
                                        ?>
                                        <div class="well-sm"><?php echo $itemAmountErr; ?></div>
                                    <?php endif ?>
                                </div>
                            </li>
                            <li>
                                <div class="well-sm">
                                    Expire Date
                                    <div class="pull-right">
                                        <?php echo $this->formElement($addForm->get('expireDate')); ?>
                                    </div>
                                    <?php
                                    $expireDateErr = $this->formElementErrors($addForm->get('expireDate'), array('class' => 'help-inline'));
                                    if ($expireDateErr != ''):
                                        ?>
                                        <div class="well-sm"><?php echo $expireDateErr; ?></div>
                                    <?php endif ?>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
               <div class="pull-right">
                    <input type="reset" value="Clear" id="addClear" name="addClear">
                    <?php echo $this->formSubmit($addForm->get('submitAdd')); ?>
                </div>
            </div>
        </div> 
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>
<script type="text/javascript">
    var jArray= <?php echo json_encode($itemNames); ?>;
    
//    for(var i=0;i<jArray.length;i++){
//        alert(jArray[i]);
//    }
    $('#addClear').click(function(e){
        document.getElementById("nameError").innerHTML="";
    });
    
    $('#submitAdd').click(function(e){
                    
            var item = $("#addItemName").val();
            
            if(jArray.indexOf(item) != -1){
                e.preventDefault();
                document.getElementById("nameError").innerHTML="item exists";
                //alert("item exists");
            }
       
    });
</script>