<?php
$title = 'Fridge';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php //echo $this->escapeHtml($message); ?>

<div class="row">
    <div class="col-md-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Sort Options</h3>
            </div>
            <div class="panel-body">
                <div class="well-sm">sort1</div>
                <div class="well-sm">sort2</div>
                <div class="well-sm">sort3</div>
                <div class="well-sm"><div class="pull-right"><input type="button" value="sort"/></div></div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Find in Fridge</h3>
            </div>
            <div class="panel-body">
                <input type="text"/>
                <div class="well-sm">
                    <div class="pull-right">
                        <input type="button" value="find"/>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Items in your Fridge</h3>
            </div>
            <div class="panel-body">
                <ul class="list-group">
                    <?php foreach ($fridgeItems as $item): ?> 
                        <?php
                            $updateForm->setAttribute('action', $this->url('fridge', array('action' => 'index')));
                            $updateForm->prepare();

                            echo $this->form()->openTag($updateForm);
//                            //echo $this->formHidden($addForm->get('itemID'));
//                            $itemID = $this->formHidden($addForm->get('itemID'));
//                            $itemID->setAttribute(array('value' => '2'));
//                            echo $itemID;
//
//                            echo $this->formHidden($addForm->get('itemName'));
//                            echo $this->formHidden($addForm->get('itemAmount'));
//                            echo $this->formHidden($addForm->get('amountType'));
//                            echo $this->formHidden($addForm->get('expireDate'));
                            echo $this->formElementErrors($addForm->get('itemID'));
                            echo $this->formElementErrors($addForm->get('itemName'));
                            echo $this->formElementErrors($addForm->get('itemAmount'));
                            echo $this->formElementErrors($addForm->get('amountType'));
                            echo $this->formElementErrors($addForm->get('expireDate'));
                        ?>  
                    <input type="hidden" name="itemID" id="itemID" value="<?php echo $this->escapeHtml($item->itemID); ?>"> 
                    <input type="hidden" name="itemName" id="itemName" value="<?php echo $this->escapeHtml($item->itemName); ?>">
                    <input type="hidden" name="itemAmount" id="itemAmount" value="<?php echo $this->escapeHtml($item->itemAmount); ?>">
                    <input type="hidden" name="amountType" id="amountType" value="<?php echo $this->escapeHtml($item->amountType); ?>">
                    <input type="hidden" name="expireDate" id="expireDate" value="<?php echo $this->escapeHtml($item->expireDate); ?>">
                        <li class="list-group-item">
                            <div class="well-sm">
                                <?php echo $this->escapeHtml($item->itemID); ?>
                                
                                <?php echo $this->escapeHtml($item->itemName); ?>
                                
                                <div class="pull-right">
                                    <?php echo $this->escapeHtml($item->itemAmount) . " " . $this->escapeHtml($item->amountType); ?> 


                                    <div id="update-btn" class="btn-group">
                                        <?php echo $this->formElement($updateForm->get('submitPlus')); ?>
                                        <?php echo $this->formElement($updateForm->get('submitMinus')); ?>
                                        <?php echo $this->formElement($updateForm->get('submitRemove')); ?>
                                    </div>

                                    <?php echo $this->escapeHtml($item->expireDate); ?>
                                </div>
                            </div>
                        </li>
                        <?php echo $this->form()->closeTag(); ?>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <?php
        $addForm->setAttribute('action', $this->url('fridge', array('action' => 'index')));
        $addForm->prepare();

        echo $this->form()->openTag($addForm);

        echo $this->formHidden($addForm->get('itemID'));
        ?>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Add Item to the Fridge</h3>
            </div>
            <div class="panel-body">
                <ul class="list-group">
                    <li class="list-group-item">
                        <div class="well-sm">
                            Item Name
                            <div class="pull-right">
                                <?php echo $this->formElement($addForm->get('itemName')); ?>
                            </div>
                        </div>
                        <?php
                        $itemNameErr = $this->formElementErrors($addForm->get('itemName'), array('class' => 'help-inline'));
                        if ($itemNameErr != ''):
                            ?>
                            <div class="well-sm"><?php echo $itemNameErr; ?></div>
                        <?php endif ?>
                    </li>

                    <li class="list-group-item">Time (estimate)
                        <ul>
                            <li>
                                <div class="well-sm">
                                    Amount
                                    <div class="pull-right">
                                        <?php echo $this->formElement($addForm->get('itemAmount')); ?>
                                        <?php echo $this->formElement($addForm->get('amountType')); ?>
                                    </div>
                                    <?php
                                    $itemAmountErr = $this->formElementErrors($addForm->get('itemAmount'), array('class' => 'help-inline'));
                                    if ($itemAmountErr != ''):
                                        ?>
                                        <div class="well-sm"><?php echo $itemAmountErr; ?></div>
                                    <?php endif ?>
                                </div>
                            </li>
                            <li>
                                <div class="well-sm">
                                    Expire Date
                                    <div class="pull-right">
                                        <?php echo $this->formElement($addForm->get('expireDate')); ?>
                                    </div>
                                    <?php
                                    $expireDateErr = $this->formElementErrors($addForm->get('expireDate'), array('class' => 'help-inline'));
                                    if ($expireDateErr != ''):
                                        ?>
                                        <div class="well-sm"><?php echo $expireDateErr; ?></div>
                                    <?php endif ?>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
                <div class="pull-right"><?php echo $this->formSubmit($addForm->get('submitAdd')); ?></div>
            </div>
        </div> 
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>
<script type="text/javascript">
//    $('#update-btn .btn').click(function(){
//        
//        var type = this.id;
//        //plus button
//        if(type == "plus"){
//            confirm("Add 1 to Item");
//        }
//        
//        //minus button
//        if(type == "minus"){
//            alert("Subtract 1 from Item");
//        }
//        
//        //remove button
//        if(type == "remove"){
//            alert("Remove Item?");
//       }
//    });
</script>