<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('food280') ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon2.ico'))
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>
</head>

<body>
<div class="mainHeader">
    <div class="headerText">
        FOOD280<br>
        Find it. Make it. Enjoy it. Share it.
    </div>
</div>
<nav class="navbar navbar-green" role="navigation">
    <div class="container">
        <a class="navbar-brand" href="<?= $this->basePath();?>">food280</a>
        <ul class="nav navbar-nav">
            <li><a href="#login">Login</a></li>
            <li><a href="./register">Register</a></li>
        </ul>
        <ul class="navbar navbar-nav navbar-right">
            <form class="navbar-form" role="search">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search Recipes">
                </div>
            </form>
        </ul>

    </div>
</nav>

<div class="container" style="width: 100%;">
    <?php echo $this->content; ?>
    <footer>
        <p>&copy; 20014 - <?php echo date('Y') ?> by food280 Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
    </footer>
    <?php echo $this->inlineScript() ?>
</div>

</body>

</html>
