<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('food280') ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Typekit -->
    <script type="text/javascript" src="//use.typekit.net/pxd1cjj.js"></script>
    <script type="text/javascript">try{Typekit.load();}catch(e){}</script>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon2.ico'))
        ->prependStylesheet($this->basePath() . '/css/globalstyle.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ->appendFile($this->basePath() . '/js/global.js', 'text/javascript');
    ; ?>
</head>

<body>
<nav class="navbar navbar-green" role="navigation">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation"</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">FOOD280</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <?php if ($this->userInfo == null) { ?>
                    <li><a href="/user/login">Login</a></li>
                    <li><a href="/user/register">Register</a></li>
                <?php } else { ?>
                    <li><a href="/recipe">Recipes</a></li>
                    <li><a href="/fridge">My Fridge</a></li>

                <?php } ?>
                <li><form class="navbar-form" id="search-form" role="search">
                    <div class="form-group">
                        <input type="text" class="form-control" id="search-tf" placeholder="Search Recipes">
                    </div>
                </form>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <?php if ($this->userInfo != null) { ?>
                <li><a href="/user/profile">Welcome, <?php echo $this->userInfo->name; ?></a></li>
                <li><a href="/user/logout">Sign Out</a></li>
                <?php } ?>
            </ul>
        </div>

</nav>

<div class="container">
    <?php echo $this->content; ?>
    <footer>
        <p>&copy; <?php echo date('Y') ?> by food280 Group. <?php echo $this->translate('All rights reserved.') ?></p>
    </footer>
    <?php echo $this->inlineScript() ?>
</div>

</body>

</html>
